# Lesson 1: Variables and Data Types

## 1.1 What Is a Variable?
Before Python, your computer has memory — billions of tiny storage slots. Without variables, you'd have to remember the exact memory address of every piece of data (like `0x7FFE3A2B`). That's impossible for humans.
A **variable** is a named label you stick on a memory slot. Python handles the rest.

> **Real-World Analogy:** Think of variables like labeled boxes in a storage room. You write `AGE` on one box, `NAME` on another. Whenever you need a value, you go to that box by its label. The box can hold different items over time — that's what makes it a *variable*.

---

## 1.2 Creating Variables in Python

Python uses the **assignment operator** `=` to create variables. The variable name goes on the left, the value on the right.
**Syntax:**
```python
variable_name = value
```
Notice there is **no type declaration**. In Java or C++ you'd write `int age = 25`. Python automatically figures out the type. This is called **dynamic typing**.

In [1]:
# Creating variables — Python infers the type automatically
age = 25
name = "Arjun"
height = 5.9
is_student = True

print(age, name, height, is_student)

25 Arjun 5.9 True


## 1.3 The Four Core Data Types

| Type    | Keyword | Example Values         | Used For                   |
|---------|---------|------------------------|----------------------------|
| Integer | `int`   | 0, 1, -5, 1000000     | Age, count, index, year    |
| Float   | `float` | 3.14, -0.5, 2.0       | Price, weight, accuracy %  |
| String  | `str`   | "hello", 'A'          | Name, text, labels         |
| Boolean | `bool`  | True, False           | Yes/no, on/off, flags      |

> **[AI/ML]** Every dataset column has a type. Patient age is `int`, blood pressure is `float`, city name is `str`, `has_diabetes` is `bool`. NumPy and Pandas are built entirely on these four types. Getting the type right determines whether your model trains correctly.

In [3]:
# Integer — whole numbers, positive or negative, no decimal
score = 100
year = 2024
temperature_celsius = -5

# Float — numbers with decimal points
model_accuracy = 0.9432
pi = 3.14159
bank_balance = 15750.50

# String — text enclosed in quotes (single or double)
city = "Ahmedabad"
country = 'India'
first_name = "Riya"

# Boolean — only two possible values: True or False
is_logged_in = True
has_passed_exam = False
model_trained = True

print(score, year, temperature_celsius)
print(model_accuracy, pi, bank_balance)
print(city, country, first_name)
print(is_logged_in, has_passed_exam, model_trained)

100 2024 -5
0.9432 3.14159 15750.5
Ahmedabad India Riya
True False True


## 1.4 Checking the Type of Any Variable

Python gives you the built-in function `type()` to check what type any value is. **Use this constantly when debugging.**

In [ ]:
age = 25
print(type(age))          # <class 'int'>

pi = 3.14
print(type(pi))           # <class 'float'>

name = "Arjun"
print(type(name))         # <class 'str'>

is_student = True
print(type(is_student))   # <class 'bool'>

## 1.5 Variable Naming Rules

| Rule | Example |
|------|---------|
| Only letters, numbers, and underscores | `user_age`, `score1`, `first_name` |
| Cannot start with a number | `1score` is **INVALID**, `score1` is valid |
| Case sensitive: `age` and `Age` are different | `age = 20` and `Age = 30` are two variables |
| Cannot use Python keywords | `if`, `for`, `while`, `True`, `False`, `class` — all forbidden |
| Use `snake_case` for multiple words | `model_accuracy` not `modelAccuracy` |

> **[PRO TIP]** A good variable name tells you exactly what's inside it without reading any other line. `model_loss` is excellent. `ml` is terrible. `x` is worst. Professional engineers spend real time choosing clear names — code is read **ten times** more than it is written.

In [ ]:
# ✅ Good variable names (professional)
user_name = 'Priya'
training_accuracy = 0.94
max_iterations = 1000
is_valid = True

print(user_name, training_accuracy, max_iterations, is_valid)

# ❌ Bad variable names — these will CRASH:
# 2name = 'Priya'     -> starts with number  -> SyntaxError
# my-name = 'Priya'   -> hyphens not allowed
# class = 'Math'      -> 'class' is a reserved keyword
# x = 5               -> meaningless, avoid

## 1.6 Common Mistakes — Lesson 1

### ❌ [MISTAKE 1] Using `=` instead of `==` for comparison
### ❌ [MISTAKE 2] Wrong Boolean casing (`true` instead of `True`)
### ❌ [MISTAKE 3] Mixing types without conversion

In [4]:
# MISTAKE 1: = is assignment, == is comparison
# if age = 25:   <- SyntaxError!
age = 25
if age == 25:
    print('You are 25')  # Correct

# MISTAKE 2: Boolean casing — True/False must be capitalised
# is_active = true   <- NameError: true is not defined
is_active = True     # Correct
result = False       # Correct
print(is_active, result)

# MISTAKE 3: Cannot concatenate str and int directly
# result = "Age is " + 25  <- TypeError
# Fix 1: explicit conversion
age = 25
result1 = "Age is " + str(age)
# Fix 2: f-string (always prefer this)
result2 = f"Age is {age}"
print(result1)
print(result2)

You are 25
True False
Age is 25
Age is 25


## 1.7 Exercises — Lesson 1

**[EXERCISE 1.1]** Create variables for your own profile: `name` (str), `age` (int), `gpa` (float), `is_employed` (bool). Print each one followed by its type.

**[EXERCISE 1.2]** Create `pi = 3.14159` and `radius = 7`. Compute the area, store it in `area`, and print the area and its type.

**[CHALLENGE 1]** Without running first — predict the output, then verify:
```python
x = 10
y = 3.0
z = x + y
print(type(z))
```
Why is `z` a float even though `x` is an int?
In Python, when you perform an arithmetic operation between an integer and a float, the result is automatically promoted to a **float** to preserve decimal precision. This is part of **Python's type coercion system.**

---
## 1.8 Checkpoint — Before Moving On
- What is a variable and why do we need it?
- Name the four core Python data types with one example each.
- What is the difference between `=` and `==`?
- Why does `True` work but `true` gives an error?
- What does `type()` return for the value `3.14`?