# Python for AI/ML Engineering
## Complete Documentation — Core Python Foundations
---
### What You Will Learned

| Lesson | Topic | Key Concepts | Status |
|--------|-------|--------------|--------|
| 1 | Variables and Types | int, float, str, bool, type() | [ ] |
| 2 | Strings In Depth | Methods, f-strings, slicing, indexing | [ ] |
| 3 | Operators | Arithmetic, comparison, logical, assignment | [ ] |
| 4 | Input and Output | input(), print(), type conversion | [ ] |
| 5 | Control Flow | if, elif, else, nested conditions | [ ] |
| 6 | Loops | for, while, break, continue, nested loops | [ ] |
| 7 | Functions | def, return, scope, parameters, docstrings | [ ] |
| 8 | Professional Habits | PEP 8, comments, debugging | [ ] |
| Project | Report Card | All Phase 1 concepts integrated | [ ] |

### How to Use This Notebook
> Every lesson is: **Concept → Analogy → Syntax → Examples → Common Mistakes → Exercises → Challenge**
>
> **[AI/ML]** — Directly used in AI/ML work — pay extra attention  
> **[MISTAKE]** — Common beginner error — memorize to avoid  
> **[PRO TIP]** — Industry best practice  
> **[EXERCISE]** — Stop reading, open a new cell and write code  
> **[CHALLENGE]** — Harder problem — figure it out yourself first  

---

# Lesson 1: Variables and Data Types

## 1.1 What Is a Variable?
Before Python, your computer has memory — billions of tiny storage slots. Without variables, you'd have to remember the exact memory address of every piece of data (like `0x7FFE3A2B`). That's impossible for humans.
A **variable** is a named label you stick on a memory slot. Python handles the rest.

> **Real-World Analogy:** Think of variables like labeled boxes in a storage room. You write `AGE` on one box, `NAME` on another. Whenever you need a value, you go to that box by its label. The box can hold different items over time — that's what makes it a *variable*.

---

## 1.2 Creating Variables in Python

Python uses the **assignment operator** `=` to create variables. The variable name goes on the left, the value on the right.
**Syntax:**
```python
variable_name = value
```
Notice there is **no type declaration**. In Java or C++ you'd write `int age = 25`. Python automatically figures out the type. This is called **dynamic typing**.

In [1]:
# Creating variables — Python infers the type automatically
age = 25
name = "Arjun"
height = 5.9
is_student = True

print(age, name, height, is_student)

25 Arjun 5.9 True


## 1.3 The Four Core Data Types

| Type    | Keyword | Example Values         | Used For                   |
|---------|---------|------------------------|----------------------------|
| Integer | `int`   | 0, 1, -5, 1000000     | Age, count, index, year    |
| Float   | `float` | 3.14, -0.5, 2.0       | Price, weight, accuracy %  |
| String  | `str`   | "hello", 'A'          | Name, text, labels         |
| Boolean | `bool`  | True, False           | Yes/no, on/off, flags      |

> **[AI/ML]** Every dataset column has a type. Patient age is `int`, blood pressure is `float`, city name is `str`, `has_diabetes` is `bool`. NumPy and Pandas are built entirely on these four types. Getting the type right determines whether your model trains correctly.

In [3]:
# Integer — whole numbers, positive or negative, no decimal
score = 100
year = 2024
temperature_celsius = -5

# Float — numbers with decimal points
model_accuracy = 0.9432
pi = 3.14159
bank_balance = 15750.50

# String — text enclosed in quotes (single or double)
city = "Ahmedabad"
country = 'India'
first_name = "Riya"

# Boolean — only two possible values: True or False
is_logged_in = True
has_passed_exam = False
model_trained = True

print(score, year, temperature_celsius)
print(model_accuracy, pi, bank_balance)
print(city, country, first_name)
print(is_logged_in, has_passed_exam, model_trained)

100 2024 -5
0.9432 3.14159 15750.5
Ahmedabad India Riya
True False True


## 1.4 Checking the Type of Any Variable

Python gives you the built-in function `type()` to check what type any value is. **Use this constantly when debugging.**

In [ ]:
age = 25
print(type(age))          # <class 'int'>

pi = 3.14
print(type(pi))           # <class 'float'>

name = "Arjun"
print(type(name))         # <class 'str'>

is_student = True
print(type(is_student))   # <class 'bool'>

## 1.5 Variable Naming Rules

| Rule | Example |
|------|---------|
| Only letters, numbers, and underscores | `user_age`, `score1`, `first_name` |
| Cannot start with a number | `1score` is **INVALID**, `score1` is valid |
| Case sensitive: `age` and `Age` are different | `age = 20` and `Age = 30` are two variables |
| Cannot use Python keywords | `if`, `for`, `while`, `True`, `False`, `class` — all forbidden |
| Use `snake_case` for multiple words | `model_accuracy` not `modelAccuracy` |

> **[PRO TIP]** A good variable name tells you exactly what's inside it without reading any other line. `model_loss` is excellent. `ml` is terrible. `x` is worst. Professional engineers spend real time choosing clear names — code is read **ten times** more than it is written.

In [ ]:
# ✅ Good variable names (professional)
user_name = 'Priya'
training_accuracy = 0.94
max_iterations = 1000
is_valid = True

print(user_name, training_accuracy, max_iterations, is_valid)

# ❌ Bad variable names — these will CRASH:
# 2name = 'Priya'     -> starts with number  -> SyntaxError
# my-name = 'Priya'   -> hyphens not allowed
# class = 'Math'      -> 'class' is a reserved keyword
# x = 5               -> meaningless, avoid

## 1.6 Common Mistakes — Lesson 1

### ❌ [MISTAKE 1] Using `=` instead of `==` for comparison
### ❌ [MISTAKE 2] Wrong Boolean casing (`true` instead of `True`)
### ❌ [MISTAKE 3] Mixing types without conversion

In [4]:
# MISTAKE 1: = is assignment, == is comparison
# if age = 25:   <- SyntaxError!
age = 25
if age == 25:
    print('You are 25')  # Correct

# MISTAKE 2: Boolean casing — True/False must be capitalised
# is_active = true   <- NameError: true is not defined
is_active = True     # Correct
result = False       # Correct
print(is_active, result)

# MISTAKE 3: Cannot concatenate str and int directly
# result = "Age is " + 25  <- TypeError
# Fix 1: explicit conversion
age = 25
result1 = "Age is " + str(age)
# Fix 2: f-string (always prefer this)
result2 = f"Age is {age}"
print(result1)
print(result2)

You are 25
True False
Age is 25
Age is 25


## 1.7 Exercises — Lesson 1

**[EXERCISE 1.1]** Create variables for your own profile: `name` (str), `age` (int), `gpa` (float), `is_employed` (bool). Print each one followed by its type.

**[EXERCISE 1.2]** Create `pi = 3.14159` and `radius = 7`. Compute the area, store it in `area`, and print the area and its type.

**[CHALLENGE 1]** Without running first — predict the output, then verify:
```python
x = 10
y = 3.0
z = x + y
print(type(z))
```
Why is `z` a float even though `x` is an int?
In Python, when you perform an arithmetic operation between an integer and a float, the result is automatically promoted to a **float** to preserve decimal precision. This is part of **Python's type coercion system.**

---
## 1.8 Checkpoint — Before Moving On
- What is a variable and why do we need it?
- Name the four core Python data types with one example each.
- What is the difference between `=` and `==`?
- Why does `True` work but `true` gives an error?
- What does `type()` return for the value `3.14`?

---
# Lesson 2: Strings In Depth

## 2.1 What Is a String?

A string is a **sequence of characters** — letters, numbers, spaces, symbols. In Python, anything inside quotes is a string. Strings are one of the most important types in data science because your data is almost always partially or fully text.

In [4]:
single_quotes = 'Hello'
double_quotes = "Hello"
both_work = "It's working!"    # single quote inside double quotes

# Multi-line strings use triple quotes
address = """
Plot 45, Satellite Area
Ahmedabad, Gujarat
"""

print(single_quotes)
print(double_quotes)
print(both_work)
print(address)

Hello
H, el, lo
It's working!

Plot 45, Satellite Area
Ahmedabad, Gujarat



## 2.2 f-Strings — The Professional Way to Format Text

The most important string tool you will use every day. An **f-string** lets you embed variables directly inside a string. **Always prefer f-strings over `+` concatenation.**

>  **[AI/ML]** When you train a model for 100 epochs, you print loss and accuracy every epoch. Every professional uses f-strings:
> ```python
> print(f'Epoch {epoch}/{total} │ Loss: {loss:.4f} │ Acc: {accuracy:.2%}')
> ```
> Learn f-strings cold.

In [13]:
name = "Riya"
age = 22
gpa = 8.7

# ❌ Old way (messy, error-prone)
print("Name: " + name + ", Age: " + str(age))

# ✅ f-string way (clean, professional)
print(f"Name: {name}, Age: {age}, GPA: {gpa}")

# f-strings can run expressions inside {}
print(f"Next year I will be {age + 1}")
print(f"GPA percentage: {gpa * 10:.1f}%")   # .1f = 1 decimal place
print(f"Score: {0.9432:.2%}")               # percentage formatting

Name: Riya, Age: 22
Name: Riya, Age: 22, GPA: 8.7
Next year I will be 23
GPA percentage: 95.7%
Score: 94.32%


## 2.3 Essential String Methods

Strings come with built-in **methods** — functions that transform them. You call them with a dot after the string.

In [17]:
text = "  hello, World!  "

# Case transformations
print(text.upper())       # '  HELLO, WORLD!  '
print(text.lower())       # '  hello, world!  '
print(text.title())       # '  Hello, World!  '

# Removing whitespace
print(text.strip())       # 'Hello, World!'
print(text.lstrip())      # 'Hello, World!  '
print(text.rstrip())      # '  Hello, World!'

# Finding and replacing
print(text.replace('World', 'Python'))  # '  Hello, Python!  '
print(text.find('World'))               # 9 (character position)
print(text.count('l'))                  # 3

# Splitting — extremely common in data processing
csv_row = 'Arjun,22,8.5,Ahmedabad'
parts = csv_row.split(',')  # ['Arjun', '22', '8.5', 'Ahmedabad']
print(parts)
print(parts[0])             # 'Arjun'

  HELLO, WORLD!  
  hello, world!  
  Hello, World!  
hello, World!
hello, World!  
  hello, World!
  hello, Python!  
9
3
['Arjun', '22', '8.5', 'Ahmedabad']
Arjun


## 2.4 String Indexing and Slicing

A string is a sequence. Each character has a **position (index)** starting from **0**. Negative indices count from the end.

```
word = "Python"
       P  y  t  h  o  n
       0  1  2  3  4  5   ← positive index
      -6 -5 -4 -3 -2 -1   ← negative index
```

**Slicing syntax:** `word[start:stop:step]` — `stop` is **exclusive** (not included).

> **[AI/ML]** You will slice arrays of thousands of rows to grab training data, validation sets, and test sets. **Exact same syntax:** `data[0:800]` for training, `data[800:]` for test. Master slicing now.

In [ ]:
word = "Python"

# Single character access
print(word[0])      # 'P'  -- first character
print(word[-1])     # 'n'  -- last character
print(word[2])      # 't'

# Slicing: word[start:stop:step]
print(word[0:3])    # 'Pyt'
print(word[2:])     # 'thon'  (to end)
print(word[:4])     # 'Pyth'  (from start)
print(word[::-1])   # 'nohtyP'  (reverse!)

## 2.5 Common Mistakes — Lesson 2

### ❌ [MISTAKE] Confusing index and position (index starts at 0)
### ❌ [MISTAKE] Strings are **immutable** — you cannot change a character in place

In [ ]:
name = "Arjun"
# Index starts at 0, NOT 1
print(name[1])   # 'r' -- NOT 'A'!
print(name[0])   # 'A' -- this is the first character

# Strings are immutable — you cannot reassign a character
word = "Hello"
# word[0] = 'J'   <- TypeError!

# Correct way: create a new string
word = 'J' + word[1:]
print(word)   # 'Jello'

## 2.6 Exercises — Lesson 2

**[EXERCISE 2.1]** Create `full_name = 'your full name here'`. Print: (1) uppercase, (2) total characters using `len()`, (3) first character, (4) last character using negative index.

**[EXERCISE 2.2]** Create `csv = 'Alice,30,Engineer,Mumbai'`. Split it by comma and print each field with a label: `Name: Alice`, `Age: 30`, etc.

**[CHALLENGE 2]** Write code that checks if a word is a palindrome (reads the same forwards and backwards). Use slicing only — no loop, no built-in reverse function.

---
# Lesson 3: Operators

## 3.1 Arithmetic Operators

The tricky ones are **floor division** (`//`) and **modulo** (`%`) — both extremely important in DSA and AI/ML.

> **[AI/ML]** Modulo (`%`) is used constantly. In training loops: `if epoch % 10 == 0: print(loss)` — print every 10th epoch. In data loading: `batch_index = sample_index % batch_size`.

In [ ]:
a = 17
b = 5

print(f"a + b  = {a + b}")    # 22   addition
print(f"a - b  = {a - b}")    # 12   subtraction
print(f"a * b  = {a * b}")    # 85   multiplication
print(f"a / b  = {a / b}")    # 3.4  division (ALWAYS returns float)
print(f"a // b = {a // b}")   # 3    floor division (drops decimal)
print(f"a % b  = {a % b}")    # 2    modulo (remainder)
print(f"a ** b = {a ** b}")   # 1419857  exponentiation

## 3.2 Comparison Operators

Comparison operators return `True` or `False`. They are the backbone of all decision-making.

| Operator | Meaning          | Example  | Result |
|----------|------------------|----------|--------|
| `==`     | Equal to         | `5 == 5` | True   |
| `!=`     | Not equal to     | `5 != 3` | True   |
| `>`      | Greater than     | `10 > 3` | True   |
| `<`      | Less than        | `2 < 1`  | False  |
| `>=`     | Greater or equal | `5 >= 5` | True   |
| `<=`     | Less or equal    | `4 <= 3` | False  |

## 3.3 Logical Operators

Logical operators **combine multiple conditions**. Essential for filtering data and controlling program flow.

In [ ]:
age = 22
has_id = True
gpa = 7.8

# and: BOTH must be True
can_vote = age >= 18 and has_id
print(f"can_vote: {can_vote}")           # True

# or: AT LEAST ONE must be True
gets_scholarship = gpa >= 9.0 or age < 20
print(f"gets_scholarship: {gets_scholarship}")   # False

# not: flips True to False and vice versa
is_minor = not (age >= 18)
print(f"is_minor: {is_minor}")           # False

## 3.4 Assignment Operators

Shorthand operators that modify a variable in place. Used in every loop and counter in real code.

In [ ]:
count = 0
count += 1    # same as count = count + 1  -> 1
count += 1    #                            -> 2
count *= 3    # same as count = count * 3  -> 6
count -= 2    #                            -> 4
count //= 2   #                            -> 2
print(f"count = {count}")

# This pattern is everywhere in AI/ML training loops:
total_loss = 0.0
batch_loss = 0.25   # example
total_loss += batch_loss   # accumulate loss across batches
print(f"total_loss = {total_loss}")

##  Exercises — Lesson 3

**[EXERCISE 3.1]** With `a = 100` and `b = 7`, compute and print: sum, difference, product, float division, floor division, remainder, and `a` raised to power 3.

**[EXERCISE 3.2]** Student has `gpa = 7.5` and `attendance = 78`. Write a condition: eligible if `gpa >= 6.0 AND attendance >= 75`. Print `True` or `False`.

**[CHALLENGE 3]** Without running it first — predict what this prints, then verify:
```python
x = 10
x += 5
x *= 2
x //= 3
print(x)
```

---
# Lesson 4: Input and Output

## 4.1 The `print()` Function — In Depth

You already know `print()`. But it has powerful options that professionals use constantly.

In [ ]:
# Basic print
print('Hello, World!')

# Printing multiple values — space between by default
name = 'Arjun'
age = 22
print(name, age)

# sep parameter: change the separator
print(name, age, sep=', ')    # Arjun, 22
print(name, age, sep=' | ')   # Arjun | 22

# end parameter: change what prints at the end (default is newline)
print('Loading', end='...')
print(' Done!')               # Loading... Done!

# f-string number formatting
pi = 3.14159265
print(f'Pi = {pi:.2f}')       # Pi = 3.14 (2 decimal places)
print(f'Pi = {pi:.4f}')       # Pi = 3.1416
print(f'Score: {0.9432:.1%}') # Score: 94.3%

## 4.2 The `input()` Function

`input()` pauses your program and waits for the user to type something. It **always returns a string**, regardless of what the user types.

> ❌ **[MISTAKE]** Forgetting to convert input — this is the **#1 beginner mistake**. You ask for a number, forget `int()`, then try to do math. Python sees a string and crashes with `TypeError`. **Always convert immediately after `input()`.**

In [ ]:
# DEMO — simulating input() with a preset value to avoid blocking the notebook
# In real usage: name = input('Enter your name: ')

name = "Priya"   # simulated input
print(f'Hello, {name}!')

# input() always returns a string — you MUST convert
age_str = "22"   # simulated input — it's a str, not int!
print(type(age_str))   # <class 'str'>

age = int(age_str)     # convert to int
print(f'In 5 years you will be {age + 5}')

height = float("1.75")  # convert to float
print(f'Height: {height}')

## 4.3 Type Conversion (Casting)

Converting between types is called **casting**. Python gives you built-in functions for it.

In [ ]:
# String to number
print(int('42'))         # 42
print(float('3.14'))     # 3.14

# Number to string
print(str(100))          # '100'
print(str(3.14))         # '3.14'

# Int/float conversion
print(int(3.9))          # 3  — truncates, does NOT round
print(float(5))          # 5.0

# Boolean conversions
print(bool(0))           # False
print(bool(1))           # True
print(bool(-100))        # True  (any non-zero is True)
print(bool(''))          # False (empty string is False)
print(bool("hello"))     # True  (non-empty string is True)

## 4.4 Exercises — Lesson 4

**[EXERCISE 4.1]** Write a program that asks for a name and birth year, calculates age (use 2025 as current year), and prints: `'Hello [name]! You are [age] years old.'`

**[CHALLENGE 4]** Create a mini calculator. Ask the user for two floats and an operator (`+`, `-`, `*`, `/`). Print the correct result. Handle division by zero with a message.

---
# Lesson 5: Control Flow — if, elif, else

## 5.1 What Is Control Flow?

By default, Python runs code top to bottom, one line at a time. **Control flow** lets you make decisions — run some code only when a condition is met, skip other code, repeat code. Without control flow, your program has no intelligence.

>  **Real-World Analogy:** Your bank's ATM uses control flow: `if balance >= withdrawal_amount` → dispense cash; `elif account_blocked` → show error; `else` → insufficient funds. Every decision-making system in the world uses this pattern.

## 5.2 The if-elif-else Structure

**Syntax:**
```python
if condition1:
    # runs if condition1 is True
elif condition2:
    # runs if condition1 is False AND condition2 is True
else:
    # runs if ALL conditions above are False
```

>  **[AI/ML]** `if model_accuracy > best_accuracy: save_model()` · `if epoch % 10 == 0: log_metrics()` · `if loss < threshold: early_stopping()`. Every ML training script is full of if-else logic.

In [ ]:
# Grade Calculator
score = 78

if score >= 90:
    grade = 'A'
elif score >= 80:
    grade = 'B'
elif score >= 70:
    grade = 'C'
elif score >= 60:
    grade = 'D'
else:
    grade = 'F'

print(f'Score: {score}, Grade: {grade}')   # Score: 78, Grade: C

## 5.3 Indentation — Python's Most Important Rule

In Python, **indentation is not optional formatting**. It defines which code belongs to which block. Use exactly **4 spaces** (Jupyter handles this automatically).

In [7]:
age = 20

if age >= 18:
    print('Adult')           # 4 spaces — inside the if block
    print('Can vote')        # also inside the if block

print('This always runs')   # no indent — outside the if block

Adult
Can vote
This always runs


## 5.4 Nested Conditions

In [8]:
age = 28
income = 45000
credit_score = 720

# Nested approach
if age >= 21:
    if income >= 30000:
        if credit_score >= 700:
            print('Loan approved')
        else:
            print('Credit score too low')
    else:
        print('Income too low')
else:
    print('Too young for loan')

# Cleaner version using 'and'
if age >= 21 and income >= 30000 and credit_score >= 700:
    print('Loan approved (clean version)')
else:
    print('Not eligible')

Loan approved
Loan approved (clean version)


## 5.5 Common Mistakes — Lesson 5

### ❌ [MISTAKE] Forgetting the colon after `if`
### ❌ [MISTAKE] Using `=` instead of `==` in condition

In [ ]:
# Both mistakes cause SyntaxError — here's the CORRECT version:
age = 20

if age > 18:          # colon is mandatory
    print('adult')

if age == 18:         # == for comparison, not =
    print('exactly 18')
else:
    print('not 18')

## 5.6 Exercises — Lesson 5

**[EXERCISE 5.1]** Take a number from the user and print: `'Positive'`, `'Negative'`, or `'Zero'`.

**[EXERCISE 5.2]** Leap year checker. A year is a leap year if: divisible by 4, BUT NOT by 100, UNLESS also divisible by 400. Test with 2000, 1900, 2024, 2023.

**[CHALLENGE 5]** Build a BMI calculator. Ask for weight (kg) and height (m). Calculate `BMI = weight / height²`. Print the category: Underweight (<18.5), Normal (18.5–24.9), Overweight (25–29.9), Obese (≥30).

---
# Lesson 6: Loops

## 6.1 Why Loops?

Imagine printing numbers 1 to 1,000,000. Without loops → 1 million `print` statements. With a loop → 2 lines. More importantly: in AI/ML you train models over thousands of iterations, process millions of data rows, and loop through every sample in your dataset. **Loops are the engine of all of that.**

## 6.2 The `for` Loop

A `for` loop iterates over a sequence — a range of numbers, a list, a string, any collection.

In [ ]:
# range(stop): 0 up to but NOT including stop
for i in range(5):
    print(i, end=' ')   # 0 1 2 3 4
print()

# range(start, stop)
for i in range(1, 6):
    print(i, end=' ')   # 1 2 3 4 5
print()

# range(start, stop, step)
for i in range(0, 20, 5):
    print(i, end=' ')   # 0 5 10 15
print()

# Looping over a string
for char in "Python":
    print(char, end=' ')   # P y t h o n
print()

In [ ]:
#  [AI/ML] Training Loop Pattern
total_epochs = 100
for epoch in range(1, total_epochs + 1):
    loss = 1.0 / epoch   # fake loss for demonstration
    if epoch % 10 == 0:
        print(f'Epoch {epoch:3d}/{total_epochs} | Loss: {loss:.4f}')

## 6.3 The `while` Loop

A `while` loop keeps running **as long as a condition is True**. Use it when you don't know in advance how many iterations you need.

> ❌ **[MISTAKE]** If you forget to update the variable inside a `while` loop, it runs forever (infinite loop). In Jupyter, click the stop button (■) or press **I** twice to interrupt the kernel.

In [4]:
# count = 1
# while count <= 5:
#     print(count, end=' ')
#     count += 1    # CRITICAL: always update the condition variable
# print()

# Pattern: keep trying until a condition is met
password = input("Enter password: ")

while password != "secret123":
    print("Wrong password. Try again.")
    password = input("Enter password: ")

print("Access granted!")

Enter password:  mohit


Wrong password. Try again.


Enter password:  secret123


Access granted!


### Pattern 1 — Counter
```
   count = 1
while count <= 5:
    print(count)
    count += 1
```    
**Use when:** counting up or down<br>
**Key:** update count inside loop

### Pattern 2 — Until Condition Met
```
   password = input("Enter password: ")
while password != "secret123":
    print("Wrong. Try again.")
    password = input("Enter password: ")

print("Access granted!")
```
**Use when:** keep asking until user gets it right<br>
**Key:** ask again inside loop to update variable

### Pattern 3 — Break When Done
```
    while True:
    password = input("Enter password: ")
    
    if password == "secret123":
        print("Access granted!")
        break
    print("Wrong. Try again.")
```
while True = run forever<br>
break      = only exit when password is correct<br>

This is actually the most common real world pattern.

#### ✅ Visual Difference Between All Three
Pattern 1 — Counter:
```
[count=1] → [count=2] → [count=3] → [count=4] → [count=5] → STOP
```
Pattern 2 — Until condition:
```
[wrong] → [wrong] → [correct] → STOP
```
Pattern 3 — Break:
```
[wrong] → [wrong] → [correct] → BREAK → STOP
```

## 6.4 Loop Control: `break`, `continue`, `pass`

In [ ]:
# break — exit the loop immediately
for i in range(10):
    if i == 5:
        break
    print(i, end=' ')   # 0 1 2 3 4
print('(break hit at 5)')

# continue — skip this iteration, move to next
for i in range(10):
    if i % 2 == 0:   # skip even numbers
        continue
    print(i, end=' ')   # 1 3 5 7 9
print()

# pass — do nothing (useful as a placeholder)
for i in range(5):
    pass   # loop runs but does nothing

## 6.5 Nested Loops

> **[AI/ML]** Processing every pixel in every image: `for image in dataset: for row in image: for pixel in row`. Nested loops are slow — later you'll learn NumPy which vectorizes this — but you must understand them first.

#### ✅ What Is A Nested Loop?
```
A loop inside another loop.
Outer loop runs ONCE → inner loop runs COMPLETELY.
Outer loop runs again → inner loop runs COMPLETELY again.

```

#### ✅ Clock Analogy
```
Outer loop = hour hand   → moves once per hour
Inner loop = minute hand → completes full 60 minutes
                           for every ONE hour move

When hour moves 1 step → minutes complete 60 steps
When outer runs 1 time → inner completes fully
```
#### ✅ Basic Structure
```
for i in range(outer):      # outer loop — controls rows
    for j in range(inner):  # inner loop — controls columns
        print(i, j)         # runs for every combination
    print()                 # moves to next line after each row
```

#### ✅ How To Trace A Nested Loop
```
for i in range(1, 4):
    for j in range(1, 4):
        print(f'{i} x {j} = {i*j}', end='   ')
    print()
```   
**Trace manually:**
```
i=1:
    j=1 → 1x1=1
    j=2 → 1x2=2
    j=3 → 1x3=3
    print() → new line
i=2:
    j=1 → 2x1=2
    j=2 → 2x2=4
    j=3 → 2x3=6
    print() → new line
i=3:
    j=1 → 3x1=3
    j=2 → 3x2=6
    j=3 → 3x3=9
    print() → new line
```
**Output:**
```
1x1=1   1x2=2   1x3=3
2x1=2   2x2=4   2x3=6
3x1=3   3x2=6   3x3=9
```
#### ✅ Variable Naming Convention

- i = outer loop variable (row)
- j = inner loop variable (column)
- This is industry standard convention
```
for i in range(rows):
    for j in range(cols):
        print(i, j)
```
**In real AI/ML code:**
```
for image in dataset:        # outer — each image
    for row in image:        # inner — each row of pixels
        for pixel in row:    # innermost — each pixel
            process(pixel)
```

***✅Key Rules***<br>

**Rule 1:** Outer loop controls ROWS
        Inner loop controls COLUMNS

**Rule 2:** Inner loop completes FULLY
        before outer loop moves once

**Rule 3:** print() after inner loop
        moves output to next line

**Rule 4:** i controls the ROW NUMBER
        j controls position WITHIN the row

**Rule 5:** Inner loop range CAN depend on i
        range(1, i+1) → grows with each row
        range(i, 0,-1) → shrinks with each row


**🐞Common Mistakes**
#### Mistake 1 — Forgetting print() for new line
```
for i in range(1, 4):
    for j in range(1, 4):
        print(i, end=' ')
# Output: 1 1 1 2 2 2 3 3 3  ← all on one line
```

#### Mistake 2 — Wrong range direction
```
for i in range(5, 0):        # ❌ missing -1
    print(i)                 # prints nothing!

for i in range(5, 0, -1):   # ✅ correct
    print(i)
```
#### Mistake 3 — Printing wrong variable
```
for i in range(1, 4):
    for j in range(1, i+1):
        print(i, end=' ')    # prints same number whole row
        # should be print(j) for increasing numbers
```
#### Mistake 4 — Hardcoding inner range
```
for i in range(1, 6):
    for j in range(1, 5):    # ❌ always 4 iterations
        print('*', end=' ')

for i in range(1, 6):
    for j in range(1, i+1):  # ✅ changes with i
        print('*', end=' ')
```


#### ✅ Four Common Patterns

In [ ]:
# Pattern 1 — Same number each row
for i in range(1, 6):
    for j in range(1, i+1):
        print(i, end=' ')     # print i
    print()
# Output:
# 1
# 2 2
# 3 3 3

# Pattern 2 — Increasing numbers each row
for i in range(1, 6):
    for j in range(1, i+1):
        print(j, end=' ')     # print j
    print()
# Output:
# 1
# 1 2
# 1 2 3

# Pattern 3 — Countdown each row
for i in range(1, 6):
    for j in range(i, 0, -1):
        print(j, end=' ')     # j counts down
    print()
# Output:
# 1
# 2 1
# 3 2 1

# Pattern 4 — Stars
for i in range(1, 6):
    for j in range(1, i+1):
        print('*', end=' ')   # print star
    print()
# Output:
# *
# * *
# * * *

#### ✅ AI/ML Connection
***Processing images — 3 nested loops***
```
for image in dataset:           # loop 1: each image
    for row in image:           # loop 2: each row of pixels
        for pixel in row:       # loop 3: each pixel value
            process(pixel)
```
 - Why nested loops are SLOW in ML:<br>
 - 1000 images × 224 rows × 224 pixels = 50,176,000 iterations<br>
 - Pure Python loops → very slow<br>

 - Solution → NumPy vectorisation (Phase 5)<br>
 - NumPy replaces all three loops with ONE line<br>
 - 100x faster because it runs in C not Python<br>

 - But you MUST understand nested loops first<br>
 - to understand what NumPy is replacing<br>

In [1]:
# Multiplication Table
for i in range(1, 4):
    for j in range(1, 4):
        print(f'{i} x {j} = {i*j}', end='   ')
    print()   # newline after each row

1 x 1 = 1   1 x 2 = 2   1 x 3 = 3   
2 x 1 = 2   2 x 2 = 4   2 x 3 = 6   
3 x 1 = 3   3 x 2 = 6   3 x 3 = 9   


## 6.6 Exercises — Lesson 6

**[EXERCISE 6.1]** Use a `for` loop to print the sum of all numbers from 1 to 100. Answer should be **5050**.

**[EXERCISE 6.2]** Print a right triangle of stars with height 5 using nested loops.

**[CHALLENGE 6]** Find all prime numbers between 1 and 50 using nested loops. A prime is divisible only by 1 and itself. Do not look up any solution.

---
# Lesson 7: Functions

## 7.1 What Is a Function?

A function is a **named, reusable block of code** that does one specific job. Instead of writing the same 10 lines in 5 different places, write it once as a function and call it 5 times.

> 🎰 **Real-World Analogy:** A function is like a vending machine. You put in input (coins + selection), it does its internal process (checks stock, dispenses), and returns output (your snack). You don't care how it works inside — you just use it. That's the beauty of functions.

## 7.2 Defining and Calling Functions

**Syntax:**
```python
def function_name(parameter1, parameter2):
    # code body (indented 4 spaces)
    return result   # optional but important
```

In [ ]:
def greet(name):
    return f'Hello, {name}!'

# Calling the function
message = greet('Priya')
print(message)             # Hello, Priya!
print(greet('Arjun'))      # Hello, Arjun!

# Function with multiple parameters
def calculate_bmi(weight_kg, height_m):
    bmi = weight_kg / (height_m ** 2)
    return round(bmi, 2)

result = calculate_bmi(70, 1.75)
print(f'BMI: {result}')    # BMI: 22.86

## 7.3 Default Parameters and Keyword Arguments

In [ ]:
# Default parameters — used when caller does not provide a value
def power(base, exponent=2):
    return base ** exponent

print(power(5))       # 25   (exponent defaults to 2)
print(power(5, 3))    # 125  (exponent is 3)

# Keyword arguments — call in any order using names
def create_user(name, age, city='Unknown'):
    return f'{name}, {age}, {city}'

print(create_user('Riya', 25, 'Mumbai'))
print(create_user(age=30, name='Arjun'))    # keyword order, city defaults

## 7.4 Return Values

In [ ]:
# A function without return returns None
def say_hi():
    print('Hi')          # no return statement

result = say_hi()        # prints 'Hi'
print(result)            # None

# Return multiple values (returns a tuple)
def min_max(numbers):
    return min(numbers), max(numbers)

low, high = min_max([3, 1, 8, 2, 7])
print(f'Min: {low}, Max: {high}')   # Min: 1, Max: 8

## 7.5 Scope — Local vs Global

A variable created **inside** a function is **local** — it exists only inside that function and disappears when the function ends. A variable created **outside** any function is **global**.

> 💡 **[PRO TIP] Avoid Global Variables** — Functions should only use their parameters and local variables. Global variables make code hard to debug and test. **Return values instead of modifying globals.** This principle becomes critical when building ML pipelines.

In [ ]:
global_var = 'I am global'

def my_function():
    local_var = 'I am local'
    print(global_var)    # Can read global
    print(local_var)     # Works fine

my_function()

print(global_var)        # Works

# print(local_var)       # NameError! local_var does not exist outside the function

## 7.6 Docstrings — Documenting Your Functions

> 💡 **[PRO TIP]** Every function you write in a real project should have a docstring. In industry, engineers read other people's code constantly. A clear docstring saves hours. Make it a habit from day one.

In [1]:
def calculate_accuracy(correct, total):
    """
    Calculate prediction accuracy as a percentage.

    Args:
        correct (int): Number of correct predictions
        total (int): Total number of predictions

    Returns:
        float: Accuracy as a value between 0 and 1
    """
    if total == 0:
        return 0.0
    return correct / total

# View the docstring
help(calculate_accuracy)

# Use it
acc = calculate_accuracy(87, 100)
print(f'Accuracy: {acc:.1%}')

Help on function calculate_accuracy in module __main__:

calculate_accuracy(correct, total)
    Calculate prediction accuracy as a percentage.

    Args:
        correct (int): Number of correct predictions
        total (int): Total number of predictions

    Returns:
        float: Accuracy as a value between 0 and 1

Accuracy: 87.0%


## 7.7 Exercises — Lesson 7

**[EXERCISE 7.1]** Write `is_even(number)` that returns `True` if even, `False` otherwise. Test with 0, 1, 4, 7, 100.

**[EXERCISE 7.2]** Write `celsius_to_fahrenheit(celsius)` using formula `F = (C * 9/5) + 32`. Test with 0, 100, and 37.

**[EXERCISE 7.3]** Write `count_vowels(word)` that returns how many vowels (a, e, i, o, u) are in the word. Make it case-insensitive.

**[CHALLENGE 7]** Write `fibonacci(n)` that returns the nth Fibonacci number. Sequence: 0, 1, 1, 2, 3, 5, 8, 13... `fibonacci(0)=0`, `fibonacci(6)=8`. Do not search for any solution.

---
# Lesson 8: Professional Coding Habits

## 8.1 Comments — When and How

Comments explain **why**, not *what*. If the code is clear enough to explain itself, don't comment it.

In [ ]:
# ❌ BAD comment: states the obvious
x = 5
x = x + 1   # add 1 to x

# ✅ GOOD comment: explains the why
x = x + 1   # compensate for 0-based indexing when displaying to user

# ❌ BAD: outdated comment (worse than no comment)
# multiply by 2
result = x * 3   # comment says 2, code does 3 -- dangerous!

# ✅ GOOD: explain business logic
credit_score = 680
# Loan rate is higher for scores below 700 per RBI guidelines
if credit_score < 700:
    interest_rate = 0.14

## 8.2 PEP 8 — Python Style Guide

**PEP 8** is the official Python style guide. Professional teams follow it. Most companies enforce it automatically.

| Rule | Example |
|------|---------|
| 4 spaces for indentation | Use 4 spaces, never tab |
| `snake_case` for variables and functions | `model_accuracy`, not `modelAccuracy` |
| `UPPER_CASE` for constants | `MAX_EPOCHS = 100`, `LEARNING_RATE = 0.01` |
| `PascalCase` for class names | `class LinearRegression:` |
| Two blank lines before a function | Separate top-level functions |
| One blank line between methods | Inside a class |
| Line length under 79 characters | Break long lines |
| Spaces around operators | `x = 5 + 3`, not `x=5+3` |
| No spaces inside brackets | `my_list[0]`, not `my_list[ 0 ]` |

## 8.3 Writing Clean, Readable Code

In [3]:
# ❌ BEFORE — Messy
def f(x,y,z):
    if x>0:
        r=y*z
        return r
    else:return 0

# ✅ AFTER — Professional
def calculate_area(is_valid, width, height):
    """Return area if valid, else 0."""
    if is_valid:
        area = width * height
        return area
    return 0

print(calculate_area(True, 5, 10))   # 50
print(calculate_area(False, 5, 10))  # 0

50
0


## 8.4 Debugging Mindset

When your code breaks (and it will, **always**), follow this process:

1. **Read the error message completely** — the last line tells you what broke.
2. **Find the line number** in the traceback.
3. **Add `print()` statements** to check variable values at each step.
4. **Narrow down:** which line does the unexpected behavior start?
5. **Fix the root cause**, not just the symptom.

In [3]:
def find_average(numbers):
    print(f'Debug: numbers = {numbers}')   # check input
    total = 0
    for num in numbers:
        total += num
        print(f'Debug: added {num}, total = {total}')  # track loop
    average = total / len(numbers)
    print(f'Debug: average = {average}')   # check output
    return average

result = find_average([10, 20, 30])
print(f'Final average: {result}')

Debug: numbers = [10, 20, 30]
Debug: added 10, total = 10
Debug: added 20, total = 30
Debug: added 30, total = 60
Debug: average = 20.0
Final average: 20.0


---
# Phase 1 Final Project: Student Report Card

This project uses **everything from Phase 1**: variables, strings, input, operators, conditionals, loops, and functions.

**Build it completely on your own.** Reference the lessons above but do not copy any code.

### Requirements:
1. Ask for a student name
2. Ask for scores in 5 subjects
3. Calculate the average
4. Assign a grade based on the average
5. Check if the student passed all subjects (minimum 40 in each)
6. Print a formatted report card

### Expected Output Format:
```
=============================
     STUDENT REPORT CARD
=============================
Student Name : Priya Sharma
Subject 1    : 85
Subject 2    : 72
Subject 3    : 90
Subject 4    : 68
Subject 5    : 55
-----------------------------
Total        : 370 / 500
Average      : 74.0
Grade        : B
Status       : PASSED
=============================
```

### Grading Scale:
**A:** 90–100 │ **B:** 80–89 │ **C:** 70–79 │ **D:** 60–69 │ **F:** Below 60

**Status is PASSED** only if average ≥ 40 AND no single subject is below 40.

---
*Write your solution in the code cell below:*

In [ ]:
# 🏆 YOUR SOLUTION HERE
# Build the Student Report Card

# Hint: start by defining helper functions, then write the main program



---
# Phase 1 Summary & Progress Tracker

## What You Have Learned

| Lesson | Topic | Key Concepts | Status |
|--------|-------|--------------|--------|
| 1 | Variables and Types | int, float, str, bool, type() | [ ] |
| 2 | Strings In Depth | Methods, f-strings, slicing, indexing | [ ] |
| 3 | Operators | Arithmetic, comparison, logical, assignment | [ ] |
| 4 | Input and Output | input(), print(), type conversion | [ ] |
| 5 | Control Flow | if, elif, else, nested conditions | [ ] |
| 6 | Loops | for, while, break, continue, nested loops | [ ] |
| 7 | Functions | def, return, scope, parameters, docstrings | [ ] |
| 8 | Professional Habits | PEP 8, comments, debugging | [ ] |
| Project | Report Card | All Phase 1 concepts integrated | [ ] |

## Phase 1 Mastery Checklist

Before you move to Phase 2, you must be able to do all of these **without looking anything up:**

- [ ] Create and name variables following PEP 8 conventions
- [ ] Explain the four core data types and when to use each
- [ ] Write f-strings with number formatting (`.2f`, `.1%`, etc.)
- [ ] Use all six comparison operators and three logical operators
- [ ] Write `if-elif-else` with proper indentation
- [ ] Write a `for` loop over a range and over a string
- [ ] Write a `while` loop that does not run infinitely
- [ ] Use `break` and `continue` correctly
- [ ] Define a function with parameters and a return value
- [ ] Explain what variable scope means
- [ ] Read a Python error message and find the root cause

---

##  What Is Coming in Phase 2

| Phase 2 Topic | Why It Matters for AI/ML |
|---------------|--------------------------|
| Lists | Foundation of NumPy arrays and data batches |
| List comprehensions | Fast, clean data transformations |
| Tuples | Immutable sequences, model shapes (e.g., `(32, 28, 28)`) |
| Dictionaries | Storing hyperparameters, configs, label maps |
| Sets | Unique values, vocabulary in NLP models |
| Nested structures | JSON data, multi-dimensional model configs |

>  **Complete the Phase 1 Final Project before moving to Phase 2.** Share your report card code with your mentor for review.